# Generated by Django 5.2.4 on 2025-08-30 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito')], max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Transação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
