# Generated by Django 5.2.4 on 2025-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, help_text='ID único do pagamento no Mercado Pago', max_length=255, null=True, verbose_name='Payment ID Mercado Pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, help_text='ID da preferência criada no Mercado Pago', max_length=255, null=True, verbose_name='Preference ID Mercado Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('recusado', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(help_text='ID da transação retornado pelo Mercado Pago', max_length=255, unique=True, verbose_name='ID da Transação'),
        ),
    ]
