# Generated by Django 5.2.4 on 2025-08-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('shirt_style', models.CharField(blank=True, max_length=100, null=True)),
                ('colors', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_files', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='em análise', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
