# Generated by Django 5.2.4 on 2025-08-06 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0002_alter_customorder_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='colors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cores'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='reference_files',
            field=models.JSONField(blank=True, null=True, verbose_name='Arquivos de Referência'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='shirt_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estilo da Camiseta'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(default='em análise', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estilo'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='urgency',
            field=models.CharField(max_length=50, verbose_name='Urgência'),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
