# Generated by Django 5.2.4 on 2025-09-01 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='product',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preco',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Sem categoria', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Produto sem título', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Indefinido', max_length=50),
        ),
    ]
